# Generated by Django 5.1.4 on 2024-12-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtors.realtor'),
        ),
    ]
